package com.dgu.prompt.blaybus_backend.googleSheetsService

import com.dgu.prompt.blaybus_backend.data.entity.FrequencyType
import com.dgu.prompt.blaybus_backend.data.entity.JobQuest2
import com.dgu.prompt.blaybus_backend.data.repository.JobQuest2Repository
import com.google.api.services.sheets.v4.Sheets
import org.springframework.stereotype.Service
import java.time.LocalDateTime

@Service
class JobQuestSheetService(
    private val sheets: Sheets,
    private val jobQuest2Repository: JobQuest2Repository
) {
    private val SPREADSHEET_ID = "1gNAIcvtjcarYJ-L9lbzno3pQqmGjdDoItNw9P324Q7c" // Google Sheets ID
    private val JOBQUESTRANGE = "참고. 직무별 퀘스트!B11:H11" // 데이터 범위
    private val CONDITIONS_RANGE = "참고. 직무별 퀘스트!F14:G14" // 조건 범위

    fun syncJobQuestData() {
        try {
            // B11:H11 데이터 가져오기
            val jobQuestResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, JOBQUESTRANGE).execute()
            val jobQuestValues = jobQuestResponse.getValues()

            // F14:G14 데이터 가져오기
            val conditionsResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, CONDITIONS_RANGE).execute()
            val conditionsValues = conditionsResponse.getValues().flatten()

            val maxCondition = conditionsValues.getOrNull(0)?.toString()
            val medianCondition = conditionsValues.getOrNull(1)?.toString()

            if (!jobQuestValues.isNullOrEmpty()) {
                val jobQuests = jobQuestValues.mapNotNull { row ->
                    try {
                        val maxExpDo = row[0].toString().toInt()
                        val medianExpDo = row[1].toString().toInt()
                        val departmentId = row[4]?.toString() ?: throw Exception("부서 ID 누락")
                        val jobGroupId = row[5]?.toString()?.toInt() ?: throw Exception("직무 그룹 ID 누락")
                        val frequencyType = if (row[6]?.toString() == "월") FrequencyType.MONTH else FrequencyType.WEEK

                        JobQuest2(
                            questId = 0, // Auto-generated by the database
                            departmentId = departmentId,
                            jobGroupId = jobGroupId,
                            maxExpDo = maxExpDo,
                            medianExpDo = medianExpDo,
                            maxCondition = maxCondition,
                            medianCondition = medianCondition,
                            description = null, // 필요 시 추가
                            updatedAt = LocalDateTime.now(),
                            frequencyType = frequencyType
                        )
                    } catch (e: Exception) {
                        println("JobQuest 데이터 변환 중 오류 발생: ${e.message}")
                        null
                    }
                }

                // 데이터 저장
                jobQuest2Repository.saveAll(jobQuests)
                println("참고. 직무별 퀘스트 Sheet 데이터를 동기화했습니다. 총 ${jobQuests.size}개 항목이 저장되었습니다.")
            } else {
                println("참고. 직무별 퀘스트 Sheet에서 데이터를 찾을 수 없습니다.")
            }
        } catch (e: Exception) {
            println("참고. 직무별 퀘스트 Sheet 동기화 중 오류 발생: ${e.message}")
        }
    }
}
