package com.dgu.prompt.blaybus_backend.googleSheetsService
//
//import com.dgu.prompt.blaybus_backend.data.entity.*
//import com.dgu.prompt.blaybus_backend.data.repository.*
//import com.google.api.services.sheets.v4.Sheets
//import org.springframework.stereotype.Service
//import java.time.LocalDateTime
//
//@Service
//class LeaderQuestSheetService(
//    private val sheets: Sheets,
//    private val leaderQuest2Repository: LeaderQuest2Repository,
//    private val departmentsRepository: DepartmentsRepository,
//    private val leaderQuestProgress2Repository: LeaderQuestProgress2Repository,
//    private val exp2Repository: Exp2Repository,
//    private val users2Repository: Users2Repository
//
//) {
//    private val SPREADSHEET_ID = "1gNAIcvtjcarYJ-L9lbzno3pQqmGjdDoItNw9P324Q7c" // Google Sheets ID
//    private val LEADERQUESTRANGE = "참고. 리더부여 퀘스트!K11:S" //K11:S 열 데이터 범위
//    private val LEADERQUESTPROGRESSRANGE = "참고. 리더부여 퀘스트!B9:H" // J10부터 R 열 데이터 범위
//    private val DEPARTMENT_CELL = "참고. 리더부여 퀘스트!K8" // K8 셀
//
//    fun syncLeaderQuestData() {
//        try {
//            // K8 셀 데이터 가져오기
//            val departmentIdResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, DEPARTMENT_CELL).execute()
//            val departmentId = departmentIdResponse.getValues().flatten().firstOrNull()?.toString()
//                ?: throw Exception(" departmentId 데이터를 가져올 수 없습니다.")
//
//            // 부서 정보 가져오기
//            val department = departmentsRepository.findById(departmentId).orElseThrow {
//                Exception("부서 ID $departmentId 에 해당하는 부서를 찾을 수 없습니다.")
//            }
//
//            // K11:S 데이터 가져오기
//            val response = sheets.spreadsheets().values().get(SPREADSHEET_ID, LEADERQUESTRANGE).execute()
//            val values = response.getValues()
//
//            if (!values.isNullOrEmpty()) {
//                val leaderQuests = values.mapNotNull { row ->
//                    try {
//                        val questTitle = row[0]?.toString() ?: throw Exception("퀘스트 제목 누락")
//                        val frequencyType = if (row[1]?.toString() == "월") FrequencyType.MONTH else FrequencyType.WEEK
//                        val maxExpDo = row[4]?.toString()?.toInt() ?: 0
//                        val medianExpDo = row[5]?.toString()?.toInt() ?: 0
//                        val maxCondition = row[6]?.toString()
//                        val medianCondition = row[7]?.toString()
//                        val description = row.getOrNull(8)?.toString() ?: ""
//
//                        LeaderQuest2(
//                            questId = 0, // Auto-generated by the database
//                            departments = department,
//                            questTitle = questTitle,
//                            description = description,
//                            maxCondition = maxCondition,
//                            medianCondition = medianCondition,
//                            maxExpDo = maxExpDo,
//                            medianExpDo = medianExpDo,
//                            updatedAt = LocalDateTime.now(),
//                            frequencyType = frequencyType
//                        )
//                    } catch (e: Exception) {
//                        println("LeaderQuest 데이터 변환 중 오류 발생: ${e.message}")
//                        null
//                    }
//                }
//
//                // 데이터 저장
//                leaderQuest2Repository.saveAll(leaderQuests)
//                println("참고. 리더 퀘스트 Sheet 데이터를 동기화했습니다. 총 ${leaderQuests.size}개 항목이 저장되었습니다.")
//            } else {
//                println("참고. 리더 퀘스트 Sheet에서 데이터를 찾을 수 없습니다.")
//            }
//        } catch (e: Exception) {
//            println("참고. 리더 퀘스트 Sheet 동기화 중 오류 발생: ${e.message}")
//        }
//    }
//
//    fun syncLeaderQuestProgressData() {
//        try {
//            // K8 셀 데이터 가져오기
//            val departmentIdResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, DEPARTMENT_CELL).execute()
//            val departmentId = departmentIdResponse.getValues().flatten().firstOrNull()?.toString()
//                ?: throw Exception("departmentId 데이터를 가져올 수 없습니다.")
//
//            // 부서 정보 가져오기
//            val department = departmentsRepository.findById(departmentId).orElseThrow {
//                Exception("부서 ID $departmentId 에 해당하는 부서를 찾을 수 없습니다.")
//            }
//
//            // Google Sheets에서 데이터 가져오기
//            val response = sheets.spreadsheets().values().get(SPREADSHEET_ID, LEADERQUESTPROGRESSRANGE).execute()
//            val values = response.getValues()
//
//            if (!values.isNullOrEmpty()) {
//                val currentTime = LocalDateTime.now()
//                val progressList = mutableListOf<LeaderQuestProgress2>()
//                val expList = mutableListOf<Exp2>()
//
//                values.forEach { row ->
//                    try {
//                        // 데이터 추출
//                        val employeeNumber = row[2].toString()
//                        val questTitle = row[5].toString()
//                        val statusString = row[4].toString()
//                        // val expDo = row[5].toString().toIntOrNull() ?: 0
//
//                        // Frequency type과 Period 설정
//                        val frequencyType = when {
//                            row.getOrNull(3)?.toString()?.isNotEmpty() == true -> FrequencyType.WEEK
//                            row.getOrNull(4)?.toString()?.isNotEmpty() == true -> FrequencyType.MONTH
//                            else -> throw IllegalArgumentException("Frequency type이 누락되었습니다.")
//                        }
//
//                        val period = when (frequencyType) {
//                            FrequencyType.WEEK -> row[3].toString().toInt()
//                            FrequencyType.MONTH -> row[4].toString().toInt()
//                        }
//
//                        // Status 변환
//                        val status = when (statusString) {
//                            "Max" -> ProgressStatus.MAX
//                            "Median" -> ProgressStatus.MEDIUM
//                            else -> throw IllegalArgumentException("Status 변환 오류: $statusString")
//                        }
//
//                        // LeaderQuest2 조회
//                        val leaderQuest2 = leaderQuest2Repository.findByDepartmentIdAndQuestTitleAndFrequencyType(
//                            departmentId = department.departmentId,
//                            questTitle = questTitle,
//                            frequencyType = frequencyType
//                        ).orElseThrow {
//                            Exception("LeaderQuest2 객체를 찾을 수 없습니다. 부서 ID: ${department.departmentId}, QuestTitle: $questTitle, FrequencyType: $frequencyType")
//                        }
//
//                        // User2 조회
//                        val users2 = users2Repository.findByEmployeeNumber(employeeNumber).orElseThrow {
//                            Exception("User2 객체를 찾을 수 없습니다. 사번: $employeeNumber")
//                        }
//
//                        // LeaderQuestProgress2 생성
//                        val leaderQuestProgress = LeaderQuestProgress2(
//                            questProgressId = 0, // Auto-generated by the database
//                            leaderQuest2 = leaderQuest2,
//                            user2 = users2,
//                            status = status,
//                            updatedAt = currentTime,
//                            period = period,
//                            frequencyType = frequencyType
//                        )
//                        progressList.add(leaderQuestProgress)
//
//
//                    } catch (e: Exception) {
//                        println("데이터 변환 중 오류 발생: ${e.message}")
//                    }
//                }
//
//                // 데이터 저장
//                leaderQuestProgress2Repository.saveAll(progressList)
//                exp2Repository.saveAll(expList)
//
//                println("리더 퀘스트 진행 현황 데이터를 동기화했습니다. 저장된 Progress: ${progressList.size}, 저장된 Exp: ${expList.size}")
//            } else {
//                println("리더 퀘스트 진행 현황 Sheet에서 데이터를 찾을 수 없습니다.")
//            }
//        } catch (e: Exception) {
//            println("리더 퀘스트 진행 현황 Sheet 동기화 중 오류 발생: ${e.message}")
//        }
//
//    }
//
//}
