package com.dgu.prompt.blaybus_backend.googleSheetsService

import com.dgu.prompt.blaybus_backend.data.entity.*
import com.dgu.prompt.blaybus_backend.data.repository.*
import com.google.api.services.sheets.v4.Sheets
import org.springframework.stereotype.Service
import java.time.LocalDateTime

@Service
class LeaderQuestSheetService(
    private val sheets: Sheets,
    private val leaderQuest2Repository: LeaderQuest2Repository,
    private val departmentsRepository: DepartmentsRepository,
    private val leaderQuestProgress2Repository: LeaderQuestProgress2Repository,
    private val exp2Repository: Exp2Repository,
    private val users2Repository: Users2Repository

) {
    private val SPREADSHEET_ID = "1gNAIcvtjcarYJ-L9lbzno3pQqmGjdDoItNw9P324Q7c" // Google Sheets ID
    private val LEADERQUESTRANGE = "참고. 리더부여 퀘스트!K11:S" //K11:S 열 데이터 범위
    private val LEADERQUESTPROGRESSRANGE = "참고. 리더부여 퀘스트!B9:I" // J10부터 R 열 데이터 범위
    private val DEPARTMENT_CELL = "참고. 리더부여 퀘스트!K8" // K8 셀

    fun syncLeaderQuestData() {
        try {
            // K8 셀 데이터 가져오기
            val departmentIdResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, DEPARTMENT_CELL).execute()
            val departmentId = departmentIdResponse.getValues().flatten().firstOrNull()?.toString()
                ?: throw Exception("departmentId 데이터를 가져올 수 없습니다.")

            // 부서 정보 가져오기
            val department = departmentsRepository.findById(departmentId).orElseThrow {
                Exception("부서 ID $departmentId 에 해당하는 부서를 찾을 수 없습니다.")
            }

            // K11:S 데이터 가져오기
            val response = sheets.spreadsheets().values().get(SPREADSHEET_ID, LEADERQUESTRANGE).execute()
            val values = response.getValues()

            if (!values.isNullOrEmpty()) {
                val leaderQuestsFromSheet = values.mapNotNull { row ->
                    try {
                        val questTitle = row[0]?.toString() ?: throw Exception("퀘스트 제목 누락")
                        val frequencyType = if (row[1]?.toString() == "월") FrequencyType.MONTH else FrequencyType.WEEK
                        val maxExpDo = row[4]?.toString()?.toInt() ?: 0
                        val medianExpDo = row[5]?.toString()?.toInt() ?: 0
                        val maxCondition = row[6]?.toString()
                        val medianCondition = row[7]?.toString()
                        val description = row.getOrNull(8)?.toString() ?: ""

                        LeaderQuest2(
                            questId = 0, // Auto-generated by the database
                            departments = department,
                            questTitle = questTitle,
                            description = description,
                            maxCondition = maxCondition,
                            medianCondition = medianCondition,
                            maxExpDo = maxExpDo,
                            medianExpDo = medianExpDo,
                            updatedAt = LocalDateTime.now(),
                            frequencyType = frequencyType
                        )
                    } catch (e: Exception) {
                        println("LeaderQuest 데이터 변환 중 오류 발생: ${e.message}")
                        null
                    }
                }

                // 기존 데이터와 비교하여 업데이트 또는 삽입
                val existingLeaderQuests = leaderQuest2Repository.findAll().associateBy { it.questTitle to it.frequencyType }

                val leaderQuestsToUpdate = leaderQuestsFromSheet.filter { newQuest ->
                    val existingQuest = existingLeaderQuests[newQuest.questTitle to newQuest.frequencyType]
                    if (existingQuest != null) {
                        // 업데이트 조건: 내용이 변경된 경우
                        existingQuest.departments != newQuest.departments ||
                                existingQuest.description != newQuest.description ||
                                existingQuest.maxCondition != newQuest.maxCondition ||
                                existingQuest.medianCondition != newQuest.medianCondition ||
                                existingQuest.maxExpDo != newQuest.maxExpDo ||
                                existingQuest.medianExpDo != newQuest.medianExpDo
                    } else {
                        true // 새로운 데이터인 경우 추가
                    }
                }.map { newQuest ->
                    val existingQuest = existingLeaderQuests[newQuest.questTitle to newQuest.frequencyType]
                    if (existingQuest != null) {
                        // 기존 데이터가 존재하는 경우 업데이트
                        existingQuest.copy(
                            departments = newQuest.departments,
                            description = newQuest.description,
                            maxCondition = newQuest.maxCondition,
                            medianCondition = newQuest.medianCondition,
                            maxExpDo = newQuest.maxExpDo,
                            medianExpDo = newQuest.medianExpDo,
                            updatedAt = LocalDateTime.now()
                        )
                    } else {
                        // 새로운 데이터는 그대로 저장
                        newQuest
                    }
                }

                if (leaderQuestsToUpdate.isNotEmpty()) {
                    leaderQuest2Repository.saveAll(leaderQuestsToUpdate)
                    println("리더 퀘스트 Sheet 데이터를 동기화했습니다. 업데이트된 항목 수: ${leaderQuestsToUpdate.size}개.")
                } else {
                    println("변경된 데이터가 없습니다.")
                }
            } else {
                println("리더 퀘스트 Sheet에서 데이터를 찾을 수 없습니다.")
            }
        } catch (e: Exception) {
            println("리더 퀘스트 Sheet 동기화 중 오류 발생: ${e.message}")
        }
    }


    fun syncLeaderQuestProgressData() {
        try {
            // K8 셀 데이터 가져오기
            val departmentIdResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, DEPARTMENT_CELL).execute()
            val departmentId = departmentIdResponse.getValues().flatten().firstOrNull()?.toString()
                ?: throw Exception("departmentId 데이터를 가져올 수 없습니다.")

            // 부서 정보 가져오기
            val department = departmentsRepository.findById(departmentId).orElseThrow {
                Exception("부서 ID $departmentId 에 해당하는 부서를 찾을 수 없습니다.")
            }

            // Google Sheets에서 데이터 가져오기
            val response = sheets.spreadsheets().values().get(SPREADSHEET_ID, LEADERQUESTPROGRESSRANGE).execute()
            val values = response.getValues()

            if (!values.isNullOrEmpty()) {
                val currentTime = LocalDateTime.now()
                val progressList = mutableListOf<LeaderQuestProgress2>()

                values.forEach { row ->
                    try {
                        // 데이터 추출
                        val employeeNumber = row[2].toString().toInt()
                        val questTitle = row[5].toString()
                        val statusString = row[4].toString()
                        val description = row.getOrNull(7)?.toString() ?: ""


                        // Frequency type과 Period 설정
                        val frequencyType = when {
                            row.getOrNull(3)?.toString()?.isNotEmpty() == true -> FrequencyType.WEEK
                            row.getOrNull(4)?.toString()?.isNotEmpty() == true -> FrequencyType.MONTH
                            else -> throw IllegalArgumentException("Frequency type이 누락되었습니다.")
                        }

                        val period = when (frequencyType) {
                            FrequencyType.WEEK -> row[3].toString().toInt()
                            FrequencyType.MONTH -> row[4].toString().toInt()
                        }

                        // Status 변환
                        val status = when (statusString) {
                            "Max" -> ProgressStatus.MAX
                            "Median" -> ProgressStatus.MEDIUM
                            else -> throw IllegalArgumentException("Status 변환 오류: $statusString")
                        }

                        // LeaderQuest2 조회
                        val leaderQuest2 = leaderQuest2Repository.findByDepartmentsAndQuestTitleAndFrequencyType(
                            departments = department,
                            questTitle = questTitle,
                            frequencyType = frequencyType
                        ).orElseThrow {
                            Exception("LeaderQuest2 객체를 찾을 수 없습니다. 부서 ID: ${department.departmentId}, QuestTitle: $questTitle, FrequencyType: $frequencyType")
                        }

                        // User2 조회
                        val users2 = users2Repository.findOptionalByEmployeeNumber(employeeNumber).orElseThrow {
                            Exception("User2 객체를 찾을 수 없습니다. 사번: $employeeNumber")
                        }

                        // LeaderQuestProgress2 생성
                        val leaderQuestProgress = LeaderQuestProgress2(
                            questProgressId = 0, // Auto-generated by the database
                            leaderQuest2 = leaderQuest2,
                            user2 = users2,
                            status = status,
                            updatedAt = currentTime,
                            period = period,
                            frequencyType = frequencyType,
                            description = description
                        )
                        progressList.add(leaderQuestProgress)

                    } catch (e: Exception) {
                        println("데이터 변환 중 오류 발생: ${e.message}")
                    }
                }

                // 데이터 저장
                leaderQuestProgress2Repository.saveAll(progressList)
                println("리더 퀘스트 진행 현황 데이터를 동기화했습니다. 저장된 Progress: ${progressList.size}")
            } else {
                println("리더 퀘스트 진행 현황 Sheet에서 데이터를 찾을 수 없습니다.")
            }
        } catch (e: Exception) {
            println("리더 퀘스트 진행 현황 Sheet 동기화 중 오류 발생: ${e.message}")
        }
    }
}
