package com.dgu.prompt.blaybus_backend.googleSheetsService

import com.dgu.prompt.blaybus_backend.data.entity.Departments
import com.dgu.prompt.blaybus_backend.data.entity.FrequencyType
import com.dgu.prompt.blaybus_backend.data.entity.LeaderQuest2
import com.dgu.prompt.blaybus_backend.data.repository.DepartmentsRepository
import com.dgu.prompt.blaybus_backend.data.repository.LeaderQuest2Repository
import com.google.api.services.sheets.v4.Sheets
import org.springframework.stereotype.Service
import java.time.LocalDateTime

@Service
class LeaderQuestSheetService(
    private val sheets: Sheets,
    private val leaderQuest2Repository: LeaderQuest2Repository,
    private val departmentsRepository: DepartmentsRepository
) {
    private val SPREADSHEET_ID = "1gNAIcvtjcarYJ-L9lbzno3pQqmGjdDoItNw9P324Q7c" // Google Sheets ID
    private val LEADERQUESTRANGE = "참고. 리더부여 퀘스트!J11:R" // J10부터 R 열 데이터 범위
    private val DEPARTMENT_CELL = "참고. 리더부여 퀘스트!J8" // J8 셀

    fun syncLeaderQuestData() {
        try {
            // J8 셀 데이터 가져오기
            val departmentIdResponse = sheets.spreadsheets().values().get(SPREADSHEET_ID, DEPARTMENT_CELL).execute()
            val departmentId = departmentIdResponse.getValues().flatten().firstOrNull()?.toString()
                ?: throw Exception("J8 셀의 데이터를 가져올 수 없습니다.")

            // 부서 정보 가져오기
            val department = departmentsRepository.findById(departmentId).orElseThrow {
                Exception("부서 ID $departmentId 에 해당하는 부서를 찾을 수 없습니다.")
            }

            // J10:R 데이터 가져오기
            val response = sheets.spreadsheets().values().get(SPREADSHEET_ID, LEADERQUESTRANGE).execute()
            val values = response.getValues()

            if (!values.isNullOrEmpty()) {
                val leaderQuests = values.mapNotNull { row ->
                    try {
                        val questTitle = row[0]?.toString() ?: throw Exception("퀘스트 제목 누락")
                        val frequencyType = if (row[1]?.toString() == "월") FrequencyType.MONTH else FrequencyType.WEEK
                        val maxExpDo = row[4]?.toString()?.toInt() ?: 0
                        val medianExpDo = row[5]?.toString()?.toInt() ?: 0
                        val maxCondition = row[6]?.toString()
                        val medianCondition = row[7]?.toString()
                        val description = row.getOrNull(8)?.toString() ?: ""

                        LeaderQuest2(
                            questId = 0, // Auto-generated by the database
                            departments = department,
                            questTitle = questTitle,
                            description = description,
                            maxCondition = maxCondition,
                            medianCondition = medianCondition,
                            maxExpDo = maxExpDo,
                            medianExpDo = medianExpDo,
                            updatedAt = LocalDateTime.now(),
                            frequencyType = frequencyType
                        )
                    } catch (e: Exception) {
                        println("LeaderQuest 데이터 변환 중 오류 발생: ${e.message}")
                        null
                    }
                }

                // 데이터 저장
                leaderQuest2Repository.saveAll(leaderQuests)
                println("참고. 리더 퀘스트 Sheet 데이터를 동기화했습니다. 총 ${leaderQuests.size}개 항목이 저장되었습니다.")
            } else {
                println("참고. 리더 퀘스트 Sheet에서 데이터를 찾을 수 없습니다.")
            }
        } catch (e: Exception) {
            println("참고. 리더 퀘스트 Sheet 동기화 중 오류 발생: ${e.message}")
        }
    }
}
