spring.application.name=blaybus-backend

# Spring Datasource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.url=jdbc:mysql://prompt.cv2mcw6ogcgy.ap-northeast-3.rds.amazonaws.com:3306/promptdb
spring.datasource.username=admin
spring.datasource.password=vmfhavmxm

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database Connection Pool Configuration (HikariCP is the default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Timezone Configuration
spring.datasource.hikari.connection-init-sql=SET time_zone = '+00:00'

# Optional: Logging SQL queries (useful for debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE